server {
    listen 80;
    server_name 216.152.156.48; # Or your VPS IP

    # Route to Next.js Website
    location / {
        proxy_pass http://website:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Route to Next.js Admin
    location /admin {
        proxy_pass http://admin:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Route to NestJS Backend
    location /api/ {
        # Note: 'backend' matches the service name in docker-compose
        proxy_pass http://backend:11111/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Route to phpMyAdmin (Optional/Security risk)
    location /pma/ {
        proxy_pass http://phpmyadmin:80/;
    }
}